### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by Kosmodows2000** [Just-a-Jason/Nostalgia-Nexus#23]
Hey there! Sorry to bother yall, but could anyone maybe tell me how to compile/run this app? I really want to run it but i have no knowlage how to compile it, and i can't find any instructions how to. Sorry for bothering once again.

**Comment by Just-a-Jason** [comment]
> Hey there! Sorry to bother yall, but could anyone maybe tell me how to compile/run this app? I really want to run it but i have no knowlage how to compile it, and i can't find any instructions how to. Sorry for bothering once again.

   Sure! Just go to: "releases > windows installer" tab. Then download .msi/exe file to and run it! 

One note:
   The files with .msi/setup.exe are installer files wich will install it on your PC. But if you want just the app you can download .exe file instead. 

Have a nice day, Jason.json 🙂
